from enum import Enum

class ReasonId(Enum):
    COMPOSITE_BONDING_CONSULTATION = "0-28-418"
    COSMETIC_CONSULTATION = "0-33-418"
    TOOTH_WHITENING_CONSULTATION = "0-36-418"
    INVISALIGN_CONSULTATION = "0-42-418"
    ORTHODONTIC_CONSULTATION = "0-44-418"
    HYGIENE_30_MINS = "0-46-418"
    CFAST_CONSULTATION = "0-43-418"
    AIR_POLISH = "0-54-418"
    HYGIENE_40_MINS = "0-47-418"
    TREATMENT_COORDINATOR_IMPLANTS = "0-48-418"
    TREATMENT_COORDINATOR_INVISALIGN = "0-49-418"
    TREATMENT_COORDINATOR_WHITENING = "0-50-418"
    HYGIENE_20_MINS = "0-53-418"
    PRIVATE_EXAM = "0-55-418"

class UserType(Enum):
    NEW_PATIENT = "NewPatient"
    EXISTING_PATIENT = "ExistingPatient"

class ProviderId(Enum):
    AYEZA_TARIQ = "AYEZA"
    CALUM_MCCALL = "CALUM"
    DR_REBECCA_SMITH = "REB"
    MUQTADEER_SYED = "MS"
    EDWARD = "HYG"
    MEENAKSHI_VENKATESH = "MV"
    SMILE_COORDINATOR = "TCO"